/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tG629CDzl62
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Layout() {
  return (
    <div className="grid min-h-screen w-full lg:grid-cols-[240px_1fr]">
      <div className="hidden lg:block bg-gray-100/40 dark:bg-gray-800/40">
        <div className="flex flex-col gap-4 p-6">
          <div className="h-[60px] flex items-center gap-2">
            <Link className="font-semibold" href="#">
              <MountainIcon className="h-6 w-6" />
              <span className="">Acme Store</span>
            </Link>
            <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
              <ShoppingCartIcon className="h-4 w-4" />
              <span className="sr-only">Shopping Cart</span>
            </Button>
          </div>
          <nav className="flex-1 overflow-auto py-2">
            <Link
              className="block rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Home
            </Link>
            <Link
              className="block rounded-lg bg-gray-100 px-3 py-2 text-gray-900  transition-all hover:text-gray-900 dark:bg-gray-800 dark:text-gray-50 dark:hover:text-gray-50"
              href="#"
            >
              Shop All
            </Link>
            <Link
              className="block rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Clothing
            </Link>
            <Link
              className="block rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Electronics
            </Link>
            <Link
              className="block rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Accessories
            </Link>
          </nav>
        </div>
      </div>
      <div className="flex flex-col gap-4 p-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div className="card">
            <div className="card-header">
              <img
                alt="Product image"
                className="w-full h-auto"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <h2 className="text-lg font-semibold">Product Name</h2>
            </div>
            <div className="card-content">
              <p className="text-gray-600">Product description goes here</p>
              <div className="flex justify-between items-center mt-4">
                <span className="text-gray-600">$99.99</span>
                <Button size="sm" variant="outline">
                  Add to Cart
                </Button>
              </div>
            </div>
          </div>
          <div className="card">
            <div className="card-header">
              <img
                alt="Product image"
                className="w-full h-auto"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <h2 className="text-lg font-semibold">Product Name</h2>
            </div>
            <div className="card-content">
              <p className="text-gray-600">Product description goes here</p>
              <div className="flex justify-between items-center mt-4">
                <span className="text-gray-600">$99.99</span>
                <Button size="sm" variant="outline">
                  Add to Cart
                </Button>
              </div>
            </div>
          </div>
          <div className="card">
            <div className="card-header">
              <img
                alt="Product image"
                className="w-full h-auto"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <h2 className="text-lg font-semibold">Product Name</h2>
            </div>
            <div className="card-content">
              <p className="text-gray-600">Product description goes here</p>
              <div className="flex justify-between items-center mt-4">
                <span className="text-gray-600">$99.99</span>
                <Button size="sm" variant="outline">
                  Add to Cart
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}
